language: cpp
sudo: required
cache:
  - ccache
os:
  - linux
  - osx
before-install:
  - |
    echo "checking cmake version"
    cmake -version
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo "Downloading CMAKE from cmake.org"
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      echo "Upgrading cmake with brew"
      brew upgrade cmake
    fi
before-script:
  - cd sources/ext/anttweakbar
  - cmake -G "Unix Makefiles"
  - make
  - cd ../cpython
  - ./configure --prefix install_debug --enable-shared --with-pydebug --with-pymalloc
  - make
  - make install
script:
  - cmake -G "Unix Makefiles"
  - make
compiler:
  - clang
  - gcc