language: cpp
sudo: required
cache:
  - ccache
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - cmake
  brew:
    packages:
      - cmake
script:
  - ROOT_DIR=`pwd`
  - |
    echo "checking cmake version"
    cmake -version
    echo "Downloading CMAKE from cmake.org"
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      CMAKE_CMD="${ROOT_DIR}/cmake/bin/cmake"
    else
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Darwin-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      CMAKE_CMD="${ROOT_DIR}/cmake/CMake.app/Contents/bin/cmake"
    fi
    echo "Finished"
  - cd sources/ext/anttweakbar/src
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then make -f Makefile; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make -f Makefile.osx; fi
  - cd  ${ROOT_DIR}/sources/ext/cpython
  - ./configure --prefix "${ROOT_DIR}/sources/ext/cpython/install_debug" --enable-shared --with-pydebug --with-pymalloc
  - make
  - make install
  - cd ${ROOT_DIR}/
  - ${CMAKE_CMD} -G "Unix Makefiles"
  - make
compiler:
  - clang
  - gcc