language: cpp
sudo: required
cache:
  - ccache
os:
  - linux
  - osx
script:
  - |
    echo "checking cmake version"
    cmake -version
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo "Downloading CMAKE from cmake.org"
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      echo "Upgrading cmake with brew"
      brew upgrade cmake
    fi
  - cd sources/ext/anttweakbar/src
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then make -f Makefile; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make -f Makefile.osx; fi
  - cd ${HOME}/Cethric/GameEngineC/sources/ext/cpython
  - ./configure --prefix "${HOME}/Cethric/GameEngineC/sources/ext/cpython/install_debug" --enable-shared --with-pydebug --with-pymalloc
  - make
  - make install
  - cd ${HOME}/Cethric/GameEngineC/
  - cmake -G "Unix Makefiles"
  - make
compiler:
  - clang
  - gcc