version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
install:
- cmd: >-
    cmake -version

    CD \D C:\projects\gameenginec\sources\ext\anttweakbar\src

    make -f Makefile

    CD \D C:\projects\gameenginec\sources\ext\cpython

    .\configure --prefix install_debug --enable-shared --with-pydebug --with-pymalloc

    make

    make install

    CD \D C:\projects\gameenginec

build:
  verbosity: minimal