version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
install:
- cmd: >-
    git submodule update --init --recursive

    cmake -version

    DIR

    CD sources\ext\anttweakbar\

    DIR

    CD  sources\ext\anttweakbar\src\

    make -f Makefile

    CD ..\cpython\

    .\configure --prefix install_debug --enable-shared --with-pydebug --with-pymalloc

    make

    make install

build:
  verbosity: minimal