version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
install:
- cmd: >-
    git submodule update --init --recursive

    cmake -version

    CD sources\ext\anttweakbar\src\

    DIR

    msbuild.exe AntTweakBar_VS2012.sln

    CD C:\projects\gameenginec\sources\ext\cpython\

    PCBuild\build.bat -p x64 -d

    CD C:\projects\gameenginec\

    cmake -G "NMake Makefiles"

    nmake.exe

build:
  verbosity: minimal