version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- x64
- x86
init:
- ps: >-
    Write-Host "Installing CMake 3.4.0 ..." -ForegroundColor Cyan

    $exePath = "$($env:USERPROFILE)\cmake-3.4.0-rc2-win32-x86.exe"

    Write-Host "Downloading..."

    (New-Object Net.WebClient).DownloadFile('https://cmake.org/files/v3.4/cmake-3.4.0-rc2-win32-x86.exe', $exePath)

    Write-Host "Installing..."

    cmd /c start /wait $exePath /S

    cmake --version

    Write-Host "CMake 3.4.0 installed" -ForegroundColor Green

install:
- cmd: >-
    git submodule update --init --recursive

    cmake -version

    CD sources\ext\anttweakbar\src\

    DIR

    msbuild.exe AntTweakBar_VS2012.sln

    CD C:\projects\gameenginec\sources\ext\cpython\

    PCBuild\build.bat -p x64 -d

    cd "\Program Files (x86)\Microsoft Visual Studio 12.0\VC"

    vcvarsall amd64_x86

    CD C:\projects\gameenginec\

    cmake -G "NMake Makefiles"

    nmake.exe

build:
  verbosity: minimal